//! Build script.
//!
//! Two jobs:
//! 1. `tauri_build` — codegen required by Tauri v2.
//! 2. Generate `builtin_manifests.rs`: the list of agent manifests embedded in the binary.
//!    The list is derived from the directory contents, so **adding a new agent is literally
//!    dropping a TOML file into `catalog/builtin/`** — no Rust code changes anywhere.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let builtin_dir = manifest_dir.join("catalog").join("builtin");

    println!("cargo:rerun-if-changed={}", builtin_dir.display());

    let mut files: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&builtin_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_file() || path.extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            let rel = format!(
                "catalog/builtin/{}",
                path.file_name().unwrap().to_string_lossy()
            );
            println!("cargo:rerun-if-changed={}", path.display());
            files.push((stem.to_string(), rel));
        }
    } else {
        println!(
            "cargo:warning=catalog/builtin not found at {}; Ahabby will ship with an empty catalog",
            builtin_dir.display()
        );
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// `(id from file stem, manifest TOML)` pairs embedded into the binary.\n\
         pub static BUILTIN_MANIFESTS: &[(&str, &str)] = &[\n",
    );
    for (stem, rel) in &files {
        code.push_str(&format!(
            "    ({:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"))),\n",
            stem, rel
        ));
    }
    code.push_str("];\n");

    write_if_changed(&out_dir.join("builtin_manifests.rs"), &code);
}

fn write_if_changed(path: &Path, contents: &str) {
    let existing = fs::read_to_string(path).unwrap_or_default();
    if existing != contents {
        fs::write(path, contents).expect("failed to write generated manifests list");
    }
}
