// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accent colour picked in Settings. `Custom` reads [`Settings::accent_custom`]; every other
 * variant maps to a preset hue the frontend owns.
 */
export type AccentColor = "clay" | "indigo" | "sky" | "teal" | "green" | "amber" | "violet" | "rose" | "graphite" | "custom";
