// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `remove_agent` did.
 */
export type AgentRemoval = { agentId: string, name: string, 
/**
 * `true` when the agent's own manifest was moved to the OS trash, `false` when the
 * agent was only hidden (and can be restored from Settings).
 */
deleted: boolean, 
/**
 * The deleted manifest, when `deleted` is `true`.
 */
path?: string | null, };
