// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { ConfigFile } from "./ConfigFile";
import type { InstallOption } from "./InstallOption";
import type { ManifestSource } from "./ManifestSource";
import type { McpServer } from "./McpServer";
import type { OtherResource } from "./OtherResource";
import type { RemovalKind } from "./RemovalKind";
import type { Skill } from "./Skill";
import type { UpdateInfo } from "./UpdateInfo";
import type { Version } from "./Version";

/**
 * The fully scanned agent — the main entity of the UI.
 */
export type Agent = { id: string, name: string, description: string, tagline?: string | null, icon?: string | null, category?: string | null, website?: string | null, docs?: string | null, 
/**
 * Who publishes the agent (from the manifest) — shown on the agent's own page.
 */
vendor?: string | null, 
/**
 * Short highlights from the manifest — shown on the agent's own page.
 */
features: Array<string>, 
/**
 * `owner/repo`, used for the repository link and the version check.
 */
github?: string | null, popular: boolean, status: AgentStatus, binaryPath?: string | null, foundIn?: string | null, version?: Version | null, 
/**
 * Method Ahabby *thinks* the agent was installed with (from the binary location).
 */
installedVia?: string | null, installOptions: Array<InstallOption>, 
/**
 * `true` when at least one install option is available on this machine.
 */
canInstall: boolean, installDocsUrl?: string | null, 
/**
 * `true` when the manifest tells us how to update this agent.
 */
canUpdate: boolean, 
/**
 * `true` when the manifest declares an uninstall command that can run on this machine,
 * so the agent can be really removed from disk instead of only hidden.
 */
canUninstall: boolean, configs: Array<ConfigFile>, skills: Array<Skill>, mcpServers: Array<McpServer>, other: Array<OtherResource>, update?: UpdateInfo | null, 
/**
 * Dotted manifest paths that still need a docs check (see `ARCHITECTURE.md`).
 */
unverified: Array<string>, notes?: string | null, manifestSource: ManifestSource, 
/**
 * What removing this agent from Ahabby would do (delete its manifest or hide it).
 */
removal: RemovalKind, 
/**
 * Non-fatal problems collected while reading this agent (bad config, missing dir, ...).
 */
warnings: Array<string>, scanMs: number, };
