// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight agent reference embedded in skills / MCP servers / configs.
 */
export type AgentRef = { id: string, name: string, icon?: string | null, };
