// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinarySpec } from "./BinarySpec";
import type { ConfigSpec } from "./ConfigSpec";
import type { InstallMethodSpec } from "./InstallMethodSpec";
import type { ManifestSource } from "./ManifestSource";
import type { McpSpec } from "./McpSpec";
import type { OtherSpec } from "./OtherSpec";
import type { SearchPathSpec } from "./SearchPathSpec";
import type { SkillSpec } from "./SkillSpec";

/**
 * The full declarative description of an agent.
 */
export type AgentManifest = { id: string, name: string, description: string, tagline?: string | null, website?: string | null, docs?: string | null, 
/**
 * Icon key resolved by the frontend (`src/shared/ui/AgentIcon.tsx`).
 */
icon?: string | null, category?: string | null, 
/**
 * Shows up in the "available to install" section even when the machine is bare.
 */
popular: boolean, 
/**
 * Who publishes the agent — shown on the agent's own page.
 */
vendor?: string | null, 
/**
 * Short, human-readable highlights shown on the agent's own page.
 */
features: Array<string>, 
/**
 * `owner/repo` used for the optional GitHub release check and the repository link.
 */
github?: string | null, 
/**
 * Which adapter implementation reads this agent. Defaults to the manifest driven
 * `ManifestAdapter`; a special adapter is opted into here (`"claude"`), so a
 * manifest can choose custom parsing rules without any registry code change.
 */
adapter?: string | null, binaries: BinarySpec, searchPaths: Array<SearchPathSpec>, configs: Array<ConfigSpec>, skills?: SkillSpec | null, mcp?: McpSpec | null, other: Array<OtherSpec>, methods: Array<InstallMethodSpec>, 
/**
 * Dotted paths of this manifest that were **not** confirmed against official docs.
 * Surfaced in the UI so the user knows what to double-check.
 */
unverified: Array<string>, 
/**
 * Free-form provenance notes (where each path comes from).
 */
notes?: string | null, source: ManifestSource, };
