// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timestamped backup of a config file.
 */
export type BackupEntry = { 
/**
 * Backup file path (the thing to restore from).
 */
path: string, 
/**
 * The file this backup belongs to.
 */
originalPath: string, createdMs: number, sizeBytes: number, };
