// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionExtract } from "./VersionExtract";

export type BinarySpec = { 
/**
 * Executable names to look for on `PATH` and in the manifest's search paths.
 */
names: Array<string>, 
/**
 * Arguments that print the version. Defaults to `--version`.
 */
versionArgs: Array<string>, versionExtract: VersionExtract, 
/**
 * Arguments that print `--help`, used for the "what is this" tooltip.
 */
helpArgs?: Array<string> | null, };
