// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * Something that went wrong while loading the catalog (builtin or user manifests).
 *
 * Problems never fail the whole scan: a broken manifest is skipped and reported,
 * so one bad file cannot take the application down.
 */
export type CatalogProblem = { severity: Severity, 
/**
 * `None` when the file could not even be parsed enough to know its id.
 */
manifestId?: string | null, 
/**
 * Dotted field path, when the problem is attributable to one manifest field.
 */
field?: string | null, source: string, message: string, };
