// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { ConfigFormat } from "./ConfigFormat";
import type { Scope } from "./Scope";

/**
 * A config file discovered on disk (or declared by a manifest but missing).
 */
export type ConfigFile = { id: string, label: string, description?: string | null, path: string, format: ConfigFormat, scope: Scope, agent: AgentRef, exists: boolean, sizeBytes?: number | null, modifiedMs?: number | null, 
/**
 * `false` when Ahabby must not write this file (binaries, caches, ...).
 */
editable: boolean, };
