// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";
import type { OsPathMap } from "./OsPathMap";
import type { Scope } from "./Scope";

/**
 * A configuration file (or directory) belonging to an agent.
 */
export type ConfigSpec = { id: string, label: string, description?: string | null, format: ConfigFormat, scope: Scope, path: OsPathMap, 
/**
 * Optional glob (relative to the resolved path) selecting several files.
 */
glob?: string | null, 
/**
 * Editors must confirm before writing when `false`.
 */
editable: boolean, };
