// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactKind } from "./FactKind";

/**
 * One value read out of one config file, ready to render.
 */
export type ConfigFact = { 
/**
 * `<config id>:<dotted key>` — stable across scans, used as the list key.
 */
id: string, kind: FactKind, 
/**
 * Dotted key path inside the document, e.g. `model` or `env.ANTHROPIC_API_KEY`.
 */
key: string, 
/**
 * The value as text, with the secret part replaced by a mask when [`ConfigFact::masked`].
 */
value: string, 
/**
 * `true` when the value carries a secret — a token, or a URL with a password in it. The
 * real text only crosses the IPC boundary through `reveal_config_fact`.
 */
masked: boolean, 
/**
 * Id of the config the value came from (matches `ConfigFile::id`).
 */
configId: string, 
/**
 * Label of that config, for the "where did this come from" hint.
 */
configLabel: string, 
/**
 * Absolute path of that config — the address `reveal_config_fact` takes back.
 */
configPath: string, };
