// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";

/**
 * The contents of a config file plus everything needed for a safe write:
 * we hand the hash back to the frontend and require it when saving, so a file
 * changed by someone else in the meantime is never silently overwritten.
 */
export type ConfigSnapshot = { path: string, format: ConfigFormat, content: string, sha256: string, sizeBytes: number, modifiedMs: number, exists: boolean, truncated: boolean, editable: boolean, };
