// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Syntax of a config file. Drives validation and the editor's grammar.
 */
export type ConfigFormat = "json" | "jsonc" | "toml" | "yaml" | "markdown" | "text";
