// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";

/**
 * Where the binary was found.
 */
export type Detection = { binaryPath: string, 
/**
 * `path` when it came from `PATH`, otherwise the manifest search path that matched.
 */
foundIn: string, 
/**
 * Which install manager that location belongs to, when recognisable.
 */
manager?: Manager | null, };
