// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified diff preview returned by `preview_config_save`.
 */
export type DiffPreview = { path: string, unified: string, added: number, removed: number, 
/**
 * Problems found by the format validator (blocking).
 */
errors: Array<string>, 
/**
 * `true` when the on-disk hash still matches the hash the editor started from.
 */
inSync: boolean, currentSha256: string, };
