// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One environment variable / header. `value` is `None` while masked, which is the
 * default: the frontend has to ask for a single value explicitly to see it.
 */
export type EnvVar = { key: string, value?: string | null, masked: boolean, };
