// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { ExtensionKind } from "./ExtensionKind";
import type { ExtensionManager } from "./ExtensionManager";
import type { ExtensionResources } from "./ExtensionResources";
import type { Scope } from "./Scope";

/**
 * One extension of an agent.
 *
 * The same shape covers the three origins so the UI renders one card: a declared package, a
 * file in the extensions directory and a built-in extension.
 */
export type Extension = { 
/**
 * Stable id: `<kind>:<short hash>` — survives a switched-off rename and a version bump.
 */
id: string, 
/**
 * Id of the `[[extensions]]` entry this row was read from. A package's files live wherever
 * the agent put them, so this — not the directory a path happens to be in — is what binds a
 * row to the surface that declared it.
 */
surface: string, name: string, description?: string | null, kind: ExtensionKind, 
/**
 * How a package is fetched; `None` for a local file or a built-in.
 */
manager?: ExtensionManager | null, 
/**
 * The source exactly as the agent declares it (`npm:foo@1.2.3`, `git:github.com/a/b`,
 * `./tools/pi-ext`, a file path, `builtin:codemode`).
 */
source: string, 
/**
 * The file or directory on disk. `None` when a package is declared but not installed.
 */
path?: string | null, 
/**
 * The entry file the agent loads, when it is file based (what Ahabby edits).
 */
entryPath?: string | null, version?: string | null, author?: string | null, homepage?: string | null, repository?: string | null, license?: string | null, 
/**
 * `false` while the agent has stopped loading it (the entry file carries the disabled
 * suffix, or the settings declare it off).
 */
enabled: boolean, 
/**
 * `true` when the agent can reconcile the package from its source.
 */
canUpdate: boolean, 
/**
 * `true` when Ahabby can remove it (a package through the agent, a local file to the trash).
 */
canRemove: boolean, 
/**
 * `true` when the entry file can be renamed aside and back.
 */
canToggle: boolean, scope: Scope, agent: AgentRef, 
/**
 * What the package ships, all four resource kinds of the agent.
 */
resources: ExtensionResources, 
/**
 * `true` when the manifest path for this extension has not been verified against docs.
 */
unverified: boolean, modifiedMs?: number | null, };
