// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a package contributes, so the UI can say "3 extensions, 2 skills" without opening it.
 */
export type ExtensionResources = { extensions: number, skills: number, prompts: number, themes: number, };
