// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An editor installed on this machine that can open a file.
 *
 * `id` is both the stable key the frontend sends back and the brand key it paints the picker's
 * icon from, so a row is recognisable before its label is read.
 */
export type ExternalEditor = { id: string, name: string, 
/**
 * The command-line shim or `.app` bundle that was found on this machine.
 */
path: string, };
