// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `set_extension_enabled` did.
 */
export type ExtensionToggle = { extensionId: string, name: string, enabled: boolean, path: string, };
