// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `delete_extension` did.
 */
export type ExtensionRemoval = { removedExtensionId: string, name: string, path: string, 
/**
 * `true` when the file went to the OS trash rather than being deleted in place.
 */
trashed: boolean, };
