// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a package is fetched. `Local` is a package declared by path rather than published.
 */
export type ExtensionManager = "npm" | "git" | "local";
