// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an agent's extensions are stored and loaded.
 *
 * Pi is the only format Ahabby reads so far: a directory of TypeScript modules plus the
 * `packages` list of a JSON settings document. An agent opts in with `[[extensions]]`; a
 * manifest without one has no extensions surface, and Ahabby says so instead of guessing.
 */
export type ExtensionFormat = "pi";
