// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an extension comes from.
 */
export type ExtensionKind = "package" | "local" | "builtin";
