// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user asked to do with one extension.
 *
 * Only the action is sent across the IPC boundary — the command line itself is resolved from
 * the manifest inside the backend, exactly like an install plan.
 */
export type ExtensionAction = "update" | "remove";
