// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionFormat } from "./ExtensionFormat";
import type { OsPathMap } from "./OsPathMap";

/**
 * Where an agent keeps its extensions.
 */
export type ExtensionSpec = { id: string, format: ExtensionFormat, 
/**
 * The extensions directory the agent discovers modules in.
 */
path: OsPathMap, 
/**
 * The JSON document whose `packages` list declares installed packages (and whose
 * `extensions` list carries the on/off overrides). Required by the `pi` format.
 */
settings?: OsPathMap | null, 
/**
 * Names of the extensions the agent itself ships. They are listed read-only, because the
 * agent owns them.
 */
builtins: Array<string>, description?: string | null, };
