// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a fact is, which decides how the UI renders it.
 */
export type FactKind = "model" | "provider" | "url" | "proxy" | "secret";
