// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Interface typeface. `Serif` is the bundled Lora; `System` uses whatever the OS ships.
 */
export type FontFamily = "inter" | "system" | "serif";
