// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key/value pair read from a skill's YAML frontmatter (order preserved).
 */
export type FrontmatterEntry = { key: string, value: string, };
