// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent the user removed from Ahabby that is still on disk (a hidden agent).
 *
 * Stored in the settings file so the Settings screen can list and restore it without a scan.
 */
export type HiddenAgent = { id: string, name: string, icon?: string | null, removedAtMs: number, };
