// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { Scope } from "./Scope";

/**
 * One place an entry the hub offers already is on this machine.
 *
 * The owner is what the Library calls it: an installed agent, the agent-neutral shared surface
 * (`shared`), or one of the user's projects (`project:<hash>`). The Hub only ever reads these —
 * the scan found them — and shows them so a card can say "you already have this, over there".
 */
export type HubEntryInstall = { 
/**
 * Who holds it: an agent, the shared surface, or a project.
 */
owner: AgentRef, 
/**
 * Where that copy belongs — global, or the project it was found in.
 */
scope: Scope, 
/**
 * The skill's own directory, or the config file holding the server entry.
 */
path: string, 
/**
 * `false` while the copy is switched off (a skill renamed to `.disabled`, a server moved into
 * the disabled container): installed and on disk, but no agent loads it right now.
 */
enabled: boolean, 
/**
 * `true` when the copy is what the source publishes right now, `false` when the two differ,
 * and `None` when they could not be compared — a source that publishes nothing to compare
 * (an `index` entry's skill is fetched only when it is opened), or a copy Ahabby could not
 * read.
 */
identical: boolean | null, };
