// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubEntryInstall } from "./HubEntryInstall";
import type { HubResourceKind } from "./HubResourceKind";

/**
 * One installable thing a source offers.
 *
 * Deliberately a description, not a payload: the list view of a source with hundreds of skills
 * is one document read away from the repository, and the bytes of one skill are only fetched
 * when the user installs it.
 */
export type HubEntry = { 
/**
 * `<source id>/<what the source calls it>` — what every command addresses.
 */
id: string, sourceId: string, sourceName: string, kind: HubResourceKind, name: string, 
/**
 * The publisher's display title, when it differs from the addressable name.
 */
title?: string | null, description?: string | null, version?: string | null, vendor?: string | null, homepage?: string | null, repository?: string | null, license?: string | null, tags: Array<string>, 
/**
 * Plugin / collection the skill sits in (`plugins/<group>/skills/<skill>`), when the
 * repository layout names one. The Hub groups cards by this and offers "install all".
 */
group?: string | null, 
/**
 * Files the install writes (skills), from the repository listing — no download needed.
 */
fileCount?: number | null, 
/**
 * Total size of those files, when the source reports it.
 */
sizeBytes?: number | null, 
/**
 * `true` when Ahabby knows how to install it.
 */
installable: boolean, 
/**
 * Why it cannot be installed, when it cannot.
 */
installProblem?: string | null, 
/**
 * How many values the install form will ask for.
 */
inputCount: number, 
/**
 * `true` when the skill carries files an agent may execute.
 */
hasScripts: boolean, 
/**
 * Places this entry is already on this machine, for which owner.
 *
 * Never the source's: the scan is what knows it, and `commands::hub` fills it in on every
 * answer, so an install anywhere — here, in the Library, in another agent's own page — shows
 * up on the card as soon as the report does.
 */
installed: Array<HubEntryInstall>, };
