// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubEntry } from "./HubEntry";
import type { HubFileInfo } from "./HubFileInfo";
import type { HubInput } from "./HubInput";
import type { HubPreview } from "./HubPreview";
import type { McpTransport } from "./McpTransport";

/**
 * One entry with everything the install dialog needs.
 */
export type HubEntryDetail = { entry: HubEntry, 
/**
 * Files the install writes, relative to the resource's own directory (skills).
 */
files: Array<HubFileInfo>, 
/**
 * The instructions themselves, for a preview before installing (skills).
 */
preview?: HubPreview | null, 
/**
 * The launch recipe, pre-filled from the entry and editable in the form (MCP servers).
 */
transport?: McpTransport | null, 
/**
 * Values the user has to supply.
 */
inputs: Array<HubInput>, 
/**
 * Where the entry's own description/documentation lives.
 */
sourceUrl?: string | null, };
