// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of payload a file of a skill is.
 *
 * The distinction is what the install dialog shows as a warning: a skill is instructions, but it
 * may also carry scripts the agent will run, and the user deserves to see that before the write.
 */
export type HubFileKind = "text" | "script" | "binary";
