// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubFileKind } from "./HubFileKind";

/**
 * One file an install would write, relative to the resource's own directory.
 */
export type HubFileInfo = { path: string, sizeBytes: number, kind: HubFileKind, };
