// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { HubResourceKind } from "./HubResourceKind";
import type { McpServer } from "./McpServer";
import type { Skill } from "./Skill";

/**
 * What an install wrote.
 */
export type HubInstall = { kind: HubResourceKind, entryId: string, 
/**
 * The owner the resource was written for.
 */
owner: AgentRef, 
/**
 * Skill directory, or the config file the server was added to.
 */
path: string, 
/**
 * How many files were written (skills).
 */
filesWritten: number, skill?: Skill | null, server?: McpServer | null, };
