// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One value the user has to supply before an MCP server can be written: an environment variable
 * of a stdio server, or a header of a remote one.
 */
export type HubInput = { key: string, description?: string | null, 
/**
 * The publisher says the server does not work without it.
 */
required: boolean, 
/**
 * The publisher marks the value as a secret (a token, a key).
 */
secret: boolean, default?: string | null, };
