// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpDraftTransport } from "./McpDraftTransport";

/**
 * What the user reviewed and confirmed in the install dialog.
 */
export type HubInstallRequest = { 
/**
 * Any owner the scan knows: an agent id, `shared`, or `project:<hash>`.
 */
ownerId: string, entryId: string, 
/**
 * Name to write it under; the entry's own name when omitted.
 */
name?: string | null, 
/**
 * The launch recipe as reviewed (and possibly edited) in the form; the entry's own recipe is
 * used when omitted. Ignored for a skill.
 *
 * It carries the environment variables or headers the user filled in, which is why the form
 * sends a whole recipe back instead of only the values: what is written is what was reviewed.
 */
transport?: McpDraftTransport | null, 
/**
 * `true` only after the dialog listed what will be written. The backend refuses the write
 * otherwise, so a UI that skips its review cannot put foreign files on disk.
 */
confirm: boolean, };
