// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubEntry } from "./HubEntry";
import type { HubSourceReport } from "./HubSourceReport";

/**
 * A page of one source's entries.
 */
export type HubPage = { entries: Array<HubEntry>, 
/**
 * What the source answered, including its own failure — one source failing is a note next
 * to its section, never a broken screen.
 */
report: HubSourceReport, fetchedAtMs: number, };
