// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontmatterEntry } from "./FrontmatterEntry";

/**
 * The entry file of a skill, read out of the collection so the user can read the instructions
 * *before* anything is written.
 *
 * It is the file an agent would load (`SKILL.md`), already split the way the UI shows a skill it
 * found on disk: the frontmatter as key/value rows and the markdown body rendered.
 */
export type HubPreview = { 
/**
 * Path of the file inside the skill's own directory.
 */
path: string, 
/**
 * Markdown body (frontmatter stripped).
 */
content: string, 
/**
 * Frontmatter of that file, in document order.
 */
frontmatter: Array<FrontmatterEntry>, 
/**
 * `true` when the file is longer than a preview carries.
 */
truncated: boolean, };
