// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubResourceKind } from "./HubResourceKind";

/**
 * What the frontend asks the hub for.
 */
export type HubQuery = { 
/**
 * Free text, matched by the source (the MCP registry searches server side) or by Ahabby.
 */
query: string, 
/**
 * Restrict to one kind of resource.
 */
kind?: HubResourceKind | null, 
/**
 * Cursor returned by the previous page of the same source.
 */
cursor?: string | null, 
/**
 * Entries per source. Clamped to [`MIN_LIMIT`]..[`MAX_LIMIT`].
 */
limit?: number | null, 
/**
 * Ignore the cache and fetch again — the "refresh" button.
 */
refresh: boolean, };
