// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a source is read. One kind per documented API/format, so a source declares *what* it is
 * and the reader knows *how* to talk to it.
 */
export type HubSourceKind = "mcpRegistry" | "githubSkills" | "index";
