// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubResourceKind } from "./HubResourceKind";
import type { HubSourceKind } from "./HubSourceKind";
import type { HubTagRule } from "./HubTagRule";

/**
 * One place a library comes from.
 */
export type HubSource = { id: string, name: string, kind: HubSourceKind, description?: string | null, 
/**
 * Kinds of resources this source offers. A source that declares neither installs nothing,
 * which the loader reports as a problem.
 */
provides: Array<HubResourceKind>, homepage?: string | null, docs?: string | null, license?: string | null, 
/**
 * Who publishes the collection — shown on an entry's card.
 */
vendor?: string | null, 
/**
 * `mcpRegistry` / `index`: where the document to read lives.
 */
url?: string | null, 
/**
 * `githubSkills`: `owner/repo`.
 */
repository?: string | null, 
/**
 * Branch, tag or commit to read. Defaults to `main`.
 */
gitRef?: string | null, 
/**
 * `githubSkills`: only skills under this repository directory are offered.
 */
path?: string | null, 
/**
 * Repository paths (directories or globs) that are never offered as skills — a template
 * skeleton, a vendored copy, an example.
 */
exclude?: Array<string>, 
/**
 * Tags every entry of this source carries, on top of whatever the entry declares itself.
 */
tags?: Array<string>, 
/**
 * Tags for the entries this source addresses by a prefix of its own name for them.
 */
tagRules?: Array<HubTagRule>, 
/**
 * `true` for a source embedded in the binary. A user source with the same id replaces it.
 */
builtin: boolean, 
/**
 * Where a user source was read from, for the UI to point at.
 *
 * Set by the loader, never by the file itself: the loader overwrites whatever it read.
 */
sourceFile?: string | null, };
