// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogProblem } from "./CatalogProblem";
import type { HubSource } from "./HubSource";

/**
 * Everything the hub knows where to look.
 */
export type HubSourceCatalog = { sources: Array<HubSource>, 
/**
 * Sources that failed to load, reported instead of silently disappearing.
 */
problems: Array<CatalogProblem>, 
/**
 * Directory a user source may be dropped into, so the UI can tell the user where.
 */
userDir: string, };
