// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubResourceKind } from "./HubResourceKind";
import type { HubSourceKind } from "./HubSourceKind";

/**
 * What one source answered, including its own failure.
 *
 * A source that times out or is down never fails the whole screen: the others are still listed,
 * and this report is what the UI shows next to the empty section.
 */
export type HubSourceReport = { id: string, name: string, kind: HubSourceKind, provides: Array<HubResourceKind>, description?: string | null, homepage?: string | null, builtin: boolean, 
/**
 * Entries in this page.
 */
count: number, 
/**
 * Entries the source holds in total, when it says so.
 */
total?: number | null, 
/**
 * Opaque cursor for the next page, when there is one.
 */
nextCursor?: string | null, 
/**
 * How long this source took to answer.
 */
durationMs: number, 
/**
 * `true` when the answer came from the in-memory cache.
 */
fromCache: boolean, 
/**
 * This source's own failure, when it failed.
 */
error?: string | null, 
/**
 * Things this source said that the user should know without it being a failure: entries an
 * index document had to skip, a payload too large to read whole.
 */
problems: Array<string>, };
