// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";

/**
 * Both sides of a skill content comparison: what the collection publishes, and what one owner
 * already holds.
 *
 * The texts are the full `SKILL.md` bytes decoded as UTF-8 — the same bytes the Hub hashes for
 * `identical` — so a truncated preview never stands in for either side.
 */
export type HubSkillCompare = { 
/**
 * The hub entry both sides belong to.
 */
entryId: string, 
/**
 * The skill's name, as the collection publishes it.
 */
name: string, 
/**
 * Who holds the local copy.
 */
owner: AgentRef, 
/**
 * Absolute path of the local `SKILL.md`.
 */
localPath: string, 
/**
 * The collection's `SKILL.md`.
 */
published: string, 
/**
 * The local `SKILL.md`.
 */
local: string, };
