// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tags a source declares for some of its entries, by prefix.
 *
 * What is compared is the source's *own* name for an entry — a skill's repository directory
 * (`skills/pdf`), an index entry's id, a registry server's name. The rule applies to that name
 * and to everything under it, so one rule tags a whole directory of skills.
 */
export type HubTagRule = { 
/**
 * The entry name, or the beginning of one, this rule is about.
 */
prefix: string, tags: Array<string>, };
