// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved, executable plan. This is the only thing the UI can ask the backend to run.
 */
export type InstallAction = "install" | "update" | "uninstall";
