// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";
import type { Os } from "./Os";

/**
 * An install / update / uninstall recipe for one package manager on one OS.
 */
export type InstallMethodSpec = { 
/**
 * Stable id the UI passes back when the user picks this method (`npm`, `brew`, ...).
 */
id: string, manager: Manager, 
/**
 * Empty means "every OS".
 */
os: Array<Os>, 
/**
 * Exact command line, executed as a program + args (never through a shell)
 * unless `manager = "script"`.
 */
command: string, updateCommand?: string | null, uninstallCommand?: string | null, docsUrl?: string | null, note?: string | null, 
/**
 * Lower runs first when several methods are available.
 */
priority: number, 
/**
 * Human readable prerequisites, e.g. `node >= 18`.
 */
requires: Array<string>, };
