// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";

/**
 * One way to install (or update) an agent, already checked against this machine.
 */
export type InstallOption = { id: string, manager: Manager, 
/**
 * Exact command line the user will be asked to confirm.
 */
command: string, updateCommand?: string | null, requires: Array<string>, docsUrl?: string | null, note?: string | null, 
/**
 * `true` when the required package manager is actually present on this machine.
 */
available: boolean, unavailableReason?: string | null, 
/**
 * `true` when this looks like the method the agent was installed with.
 */
detected: boolean, };
