// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallAction } from "./InstallAction";
import type { Manager } from "./Manager";
import type { Os } from "./Os";

export type InstallPlan = { agentId: string, agentName: string, action: InstallAction, methodId: string, manager: Manager, program: string, args: Array<string>, 
/**
 * Exactly what the user will confirm, with quoting preserved.
 */
displayCommand: string, 
/**
 * `true` when the command is executed through the platform shell (script methods).
 */
usesShell: boolean, managerAvailable: boolean, warnings: Array<string>, targetOs: Os, };
