// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamKind } from "./StreamKind";

export type JobOutputEvent = { jobId: string, stream: StreamKind, line: string, };
