// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallAction } from "./InstallAction";

export type JobOutcome = { jobId: string, agentId: string, action: InstallAction, command: string, ok: boolean, exitCode: number | null, cancelled: boolean, durationMs: number, message?: string | null, };
