// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogProblem } from "./CatalogProblem";
import type { LibraryStats } from "./LibraryStats";
import type { McpServer } from "./McpServer";
import type { OtherResource } from "./OtherResource";
import type { Skill } from "./Skill";

/**
 * Aggregated view across every agent: the "Library" tab.
 */
export type Library = { skills: Array<Skill>, mcpServers: Array<McpServer>, other: Array<OtherResource>, stats: LibraryStats, scannedAtMs: number, problems: Array<CatalogProblem>, };
