// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryStats = { agents: number, installedAgents: number, skills: number, mcpServers: number, other: number, };
