// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Package managers (and installers) Ahabby knows how to drive.
 */
export type Manager = "npm" | "pnpm" | "yarn" | "bun" | "brew" | "winget" | "scoop" | "pipx" | "pip" | "cargo" | "go" | "script" | "manual";
