// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * A problem found while validating a manifest.
 */
export type ManifestProblem = { severity: Severity, field: string, message: string, };
