// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpKeyValue } from "./McpKeyValue";

/**
 * Transport of a server the user is creating. The concrete entry shape is the manifest's
 * ([`McpEntryShape`]): the same form writes the shared convention or opencode's `type: local`.
 */
export type McpDraftTransport = { "type": "stdio", command: string, args: Array<string>, env: Array<McpKeyValue>, } | { "type": "http", url: string, headers: Array<McpKeyValue>, };
