// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape of one entry in an agent's MCP config.
 *
 * Ahabby reads every family of shapes it knows (`adapters::mcp_parse`), but *writing* needs to
 * know which one an agent expects — a wrong shape is a config the agent rejects, not a server
 * it ignores. Only the agents that differ from the shared convention declare this.
 */
export type McpEntryShape = "command" | "local" | "vscode" | "list";
