// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One environment variable / header the user typed into the creation form.
 *
 * Unlike [`EnvVar`] the value is always present and never masked: it comes from the form,
 * not from a file Ahabby read.
 */
export type McpKeyValue = { key: string, value: string, };
