// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `delete_mcp_server` removed.
 */
export type McpRemoval = { removedServerId: string, name: string, 
/**
 * Config file it was removed from.
 */
config: string, };
