// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";
import type { OsPathMap } from "./OsPathMap";

/**
 * Where an agent keeps its MCP servers.
 */
export type McpSpec = { format: ConfigFormat, path: OsPathMap, 
/**
 * Glob (relative to `path`, which is then a directory) selecting the file(s) that hold
 * the servers — `opencode.json*` matches `opencode.json` and `opencode.jsonc`.
 */
glob?: string | null, 
/**
 * Path inside the parsed document that holds the `name -> server` map,
 * e.g. `["mcpServers"]` or `["mcp_servers"]`.
 */
keyPath: Array<string>, description?: string | null, 
/**
 * `true` when the document is also listed as a config file (common case).
 */
sharedWithConfig: boolean, };
