// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { EnvVar } from "./EnvVar";
import type { McpTransport } from "./McpTransport";
import type { Scope } from "./Scope";

/**
 * An MCP server entry found in an agent's config.
 */
export type McpServer = { id: string, name: string, transport: McpTransport, scope: Scope, agent: AgentRef, 
/**
 * Config file the entry lives in.
 */
sourceConfig: string, 
/**
 * Path inside the document (`["mcpServers", "github"]`) — needed to delete exactly this entry.
 */
keyPath: Array<string>, env: Array<EnvVar>, headers: Array<EnvVar>, 
/**
 * Server entry as JSON, **already redacted** server side.
 */
raw: string, 
/**
 * Creation time of the config file the entry lives in, when the platform reports one.
 */
createdMs?: number | null, 
/**
 * Modification time of that same file.
 */
modifiedMs?: number | null, hasSecrets: boolean, 
/**
 * `false` while the user has the server switched off: the entry lives in the sibling
 * `<container>Disabled` object of the same config file, where no agent looks for servers.
 * `key_path` always addresses the entry's *enabled* position, so the switch can go back.
 */
enabled: boolean, removable: boolean, unverified: boolean, };
