// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpDraftTransport } from "./McpDraftTransport";

/**
 * What the frontend sends to create an MCP server of its own.
 *
 * The entry is written into the config file the manifest already declares, at the
 * `name -> server` position the reader uses, so the new server is a first-class entry from
 * the moment it is written (switchable and removable like any other).
 */
export type McpServerDraft = { 
/**
 * Key the entry is stored under (`mcpServers.<name>`).
 */
name: string, transport: McpDraftTransport, };
