// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport of an MCP server, normalised across the many shapes agents use.
 */
export type McpTransport = { "type": "stdio", command: string, args: Array<string>, } | { "type": "http", url: string, 
/**
 * `http`, `sse`, `streamable-http` or whatever the config called it.
 */
protocol: string, } | { "type": "unknown", detail: string, };
