// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `set_mcp_server_enabled` switched.
 */
export type McpToggle = { serverId: string, name: string, 
/**
 * The state the server is in now.
 */
enabled: boolean, 
/**
 * Config file the entry was moved inside.
 */
config: string, };
