// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typeface used for code, paths and the config editor.
 */
export type MonoFont = "jetbrains" | "system";
