// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanReport } from "./ScanReport";

/**
 * A mutation result plus the state of the world afterwards.
 */
export type MutationResult<T> = { 
/**
 * Payload of the mutation (a save result, removal details, ...).
 */
data: T, 
/**
 * Fresh scan, so the UI never shows a stale file list.
 */
report: ScanReport, };
