// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host operating system, as far as the catalog cares.
 */
export type Os = "windows" | "macos" | "linux";
