// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A path that may differ per OS. `${VAR}` placeholders are expanded by `platform::paths`.
 */
export type OsPathMap = { windows?: string | null, macos?: string | null, linux?: string | null, };
