// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-config resources: instructions, slash commands, sub-agents, hooks, rules.
 */
export type OtherKind = "instructions" | "commands" | "subagents" | "hooks" | "rules" | "prompts" | "memory";
