// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { ConfigFormat } from "./ConfigFormat";
import type { OtherKind } from "./OtherKind";
import type { Scope } from "./Scope";

/**
 * Everything that is neither a config file nor a skill nor an MCP server:
 * instructions (`CLAUDE.md`, `AGENTS.md`), slash commands, sub-agents, hooks, rules.
 */
export type OtherResource = { id: string, kind: OtherKind, label: string, path: string, agent: AgentRef, scope: Scope, format: ConfigFormat, description?: string | null, 
/**
 * Markdown/text preview for files small enough to show inline.
 */
content?: string | null, sizeBytes?: number | null, 
/**
 * Creation time of the file (or the directory itself), when the platform reports one.
 */
createdMs?: number | null, 
/**
 * Modification time of the same entry.
 */
modifiedMs?: number | null, isDirectory: boolean, exists: boolean, 
/**
 * Number of entries inside a directory resource.
 */
itemCount?: number | null, unverified: boolean, };
