// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFormat } from "./ConfigFormat";
import type { OsPathMap } from "./OsPathMap";
import type { OtherKind } from "./OtherKind";
import type { Scope } from "./Scope";

export type OtherSpec = { id: string, kind: OtherKind, label: string, path: OsPathMap, format: ConfigFormat, glob?: string | null, scope: Scope, description?: string | null, };
