// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";

/**
 * A package manager available on this machine (Settings page).
 */
export type PackageManagerInfo = { manager: Manager, program: string, path: string, };
