// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectFolder } from "./ProjectFolder";

/**
 * What one added folder turned out to be on this machine.
 */
export type ProjectFolderStatus = { folder: ProjectFolder, 
/**
 * Canonical path, when the directory could be resolved.
 */
resolved?: string | null, 
/**
 * `false` for a folder that has been moved or deleted: it is kept in Settings (the user
 * may be on a machine where a drive is not mounted) and reported as missing.
 */
exists: boolean, 
/**
 * Why this folder contributed nothing, when something went wrong.
 */
problem?: string | null, };
