// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One folder the user added to Ahabby. Stored in the settings file.
 */
export type ProjectFolder = { 
/**
 * Stable id derived from the normalized path, so adding the same folder twice is caught.
 */
id: string, 
/**
 * The folder as the user entered it.
 */
path: string, addedAtMs: number, };
