// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { ProjectFolderStatus } from "./ProjectFolderStatus";

/**
 * The whole project surface: the added folders and the projects found inside them.
 */
export type ProjectScan = { folders: Array<ProjectFolderStatus>, projects: Array<Project>, scannedAtMs: number, durationMs: number, };
