// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFile } from "./ConfigFile";
import type { McpServer } from "./McpServer";
import type { OtherResource } from "./OtherResource";
import type { Skill } from "./Skill";

/**
 * One project discovered under an added folder.
 */
export type Project = { 
/**
 * Owner id (`project:<hash>`) every resource of this project points at.
 */
id: string, 
/**
 * Display name: the directory's own name.
 */
name: string, root: string, 
/**
 * The added folder this project was discovered under.
 */
folderId: string, skills: Array<Skill>, mcpServers: Array<McpServer>, other: Array<OtherResource>, 
/**
 * Project files Ahabby may address in the editor (`AGENTS.md`, `.mcp.json`, settings…).
 */
configs: Array<ConfigFile>, 
/**
 * Newest modification time among the resources found, when the platform reports one.
 */
modifiedMs?: number | null, 
/**
 * Non-fatal problems collected while reading this project.
 */
warnings: Array<string>, scanMs: number, };
