// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Ahabby reaches the network.
 */
export type ProxyMode = "none" | "system" | "manual";
