// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user picked in the removal dialog.
 *
 * Hiding is always possible; deleting a user manifest or uninstalling the agent is a
 * separate, explicit choice the UI only offers when the backend says it is possible.
 */
export type RemovalMode = "hide" | "delete";
