// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteItem } from "./RemoteItem";

/**
 * The cloud half of the Sync library.
 */
export type RemoteList = { items: Array<RemoteItem>, fetchedAtMs: number, fromCache: boolean, };
