// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncKind } from "./SyncKind";
import type { SyncOwnerKind } from "./SyncOwnerKind";

/**
 * The cloud's own record of one pushed item.
 */
export type RemoteItem = { 
/**
 * Provider id of the remote copy (a gist id).
 */
remoteId: string, key: string, ownerId: string, ownerName: string, ownerKind: SyncOwnerKind, kind: SyncKind, name: string, label: string, relativePath: string, isDirectory: boolean, files: number, sizeBytes: number, hash: string, description: string, uri: string, updatedAtMs: number, 
/**
 * `true` when the payload declared secret-looking content (recorded at push time).
 */
hasSecrets: boolean, };
