// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful write.
 */
export type SaveResult = { path: string, sha256: string, modifiedMs: number, sizeBytes: number, 
/**
 * Path of the timestamped backup taken before the write.
 */
backupPath?: string | null, };
