// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { CatalogProblem } from "./CatalogProblem";
import type { Os } from "./Os";
import type { ProjectScan } from "./ProjectScan";
import type { SharedResources } from "./SharedResources";

/**
 * Result of one full scan.
 */
export type ScanReport = { agents: Array<Agent>, problems: Array<CatalogProblem>, scannedAtMs: number, durationMs: number, installed: number, availableToInstall: number, os: Os, 
/**
 * Resources that belong to no single agent: global skills, MCP servers and documents
 * from the cross-agent locations (`~/.agents/...`). Shown by the Library; never part of
 * the agent list or its counts.
 */
shared: SharedResources, 
/**
 * The projects the user added in the Projects screen: their folders and what each of them
 * holds. Read the same way, but they are the user's own working directories rather than
 * this machine's agents, so they never mix into the agent list, its counts or the Library.
 */
projects: ProjectScan, };
