// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { CatalogProblem } from "./CatalogProblem";
import type { Os } from "./Os";

/**
 * Result of one full scan.
 */
export type ScanReport = { agents: Array<Agent>, problems: Array<CatalogProblem>, scannedAtMs: number, durationMs: number, installed: number, availableToInstall: number, os: Os, };
