// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a config / skill / MCP server lives.
 *
 * v1 only surfaces `Global`, but the whole data model carries `Scope` so project
 * level entities can be enabled later without a migration.
 */
export type Scope = { "kind": "global" } | { "kind": "project", root: string, };
