// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extra directories to search for an agent's binary, per OS.
 *
 * Unlike [`OsPathMap`] (a single location per OS) a search path entry is naturally plural:
 * one OS often has several places a CLI can end up in.
 */
export type SearchPathSpec = { windows: Array<string>, macos: Array<string>, linux: Array<string>, };
