// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { FontFamily } from "./FontFamily";
import type { HiddenAgent } from "./HiddenAgent";
import type { Language } from "./Language";
import type { MonoFont } from "./MonoFont";
import type { ProjectFolder } from "./ProjectFolder";
import type { ProxyMode } from "./ProxyMode";
import type { SyncSettings } from "./SyncSettings";
import type { TerminalTheme } from "./TerminalTheme";
import type { Theme } from "./Theme";

export type Settings = { language: Language, theme: Theme, 
/**
 * Accent colour of the interface.
 */
accent: AccentColor, 
/**
 * `#rrggbb` used when `accent` is [`AccentColor::Custom`]; ignored otherwise.
 */
accentCustom: string | null, 
/**
 * Percent that scales spacing, controls, icons and corner radii.
 */
interfaceScale: number, 
/**
 * Percent that scales type only.
 */
textScale: number, 
/**
 * Interface typeface.
 */
fontFamily: FontFamily, 
/**
 * Typeface used for code, paths and the config editor.
 */
monoFont: MonoFont, 
/**
 * Extra directories that are searched for agent binaries and configs.
 */
extraScanPaths: Array<string>, 
/**
 * Turns the optional "a newer version exists" checks on/off (no network by default
 * is *not* the default: they are on, but never block a scan).
 */
networkVersionChecks: boolean, 
/**
 * Overrides where backups go. `None` means `<app data>/backups`.
 */
backupDir: string | null, 
/**
 * How long a version check result is reused.
 */
versionCacheMinutes: number, 
/**
 * How Ahabby reaches the network. Defaults to a direct connection.
 */
proxyMode: ProxyMode, 
/**
 * Manual proxy URL (`http://host:port`); only read when `proxy_mode` is `manual`.
 */
proxyUrl: string | null, 
/**
 * Agents the user removed from Ahabby that are still on disk. A shipped agent (or a
 * user manifest that overrides one) can only be hidden, never deleted.
 */
hiddenAgents: Array<HiddenAgent>, 
/**
 * Agent ids the user pinned as favourites, in the order they were added. The list is
 * what puts them first in the agents list and in the sidebar.
 */
favoriteAgents: Array<string>, 
/**
 * Where "run in terminal" sends an agent: `"builtin"` for Ahabby's own terminal, or the
 * id of an external terminal from `platform::terminals` (checked against the table here,
 * so a hand-edited file cannot smuggle in an unknown program).
 */
terminal: string, 
/**
 * Colours of the built-in terminal.
 */
terminalTheme: TerminalTheme, 
/**
 * Folders the user added to the Projects screen. Ahabby looks for projects inside each of
 * them (and treats the folder itself as one when it holds none) and reads the project-local
 * skills, MCP servers and documents it finds. Only Ahabby's own list changes — nothing is
 * written until the user edits something inside a project.
 */
projectFolders: Array<ProjectFolder>, 
/**
 * Whether Ahabby starts with the system: the login item is registered on save and taken
 * back when this goes off. The one setting here that changes something *outside* the app
 * config directory, which is why [`SettingsService::save`] is not the one that applies it —
 * see `desktop::autostart`.
 */
launchAtLogin: boolean, 
/**
 * Whether Ahabby keeps an icon in the system tray. The tray is what a minimized Ahabby is
 * reached through, so turning it off also turns off the two settings below.
 */
trayIcon: boolean, 
/**
 * Whether the window's close button hides Ahabby in the tray instead of quitting it. The
 * window is not closed at all, so the webview, the scan and any running install survive.
 */
closeToTray: boolean, 
/**
 * Whether a launch opens the window on screen. Off means Ahabby comes up in the tray
 * (unless the tray could not be created, when the window is shown anyway so the user is
 * never left with a process that has no surface).
 */
startMinimized: boolean, 
/**
 * Interface state the shell remembers between launches — *not* something the Settings page
 * edits. The settings document is the one place Ahabby persists anything, so "where was I"
 * lives here too instead of in a second file; [`SettingsService::save`] deliberately keeps
 * whatever these two fields already hold, so a whole-document save from the Settings page
 * (whose copy predates the last collapse or navigation) cannot roll them back.
 *
 * Whether the sidebar rail is collapsed.
 */
sidebarCollapsed: boolean, 
/**
 * The screen the window was on (`/agents`, `/settings/terminal`, …). `None` opens the home
 * screen. `boot()` reads it before the first render, so the app opens where the user left
 * it instead of painting home and navigating away.
 */
lastRoute: string | null, 
/**
 * Whether the product tour has been finished or skipped. Shell-owned like the rail: a
 * whole-document save keeps whatever this field already holds. Older settings files that
 * omit the key deserialize as completed so an upgrade does not re-show the tour; a brand-new
 * install starts with [`Settings::default`]'s `false`.
 */
tourCompleted: boolean, 
/**
 * Cloud sync: whether it is on, where copies are kept and what an automatic run covers.
 *
 * Non-secret by construction — the token lives in its own file (`sync/credentials.json`),
 * which the frontend never reads. A settings file written before the feature existed has no
 * `sync` key and deserializes as [`SyncSettings::default`] (off, manual).
 */
sync: SyncSettings, };
