// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { Theme } from "./Theme";

export type Settings = { language: Language, theme: Theme, 
/**
 * Extra directories that are searched for agent binaries and configs.
 */
extraScanPaths: Array<string>, 
/**
 * Turns the optional "a newer version exists" checks on/off (no network by default
 * is *not* the default: they are on, but never block a scan).
 */
networkVersionChecks: boolean, 
/**
 * Overrides where backups go. `None` means `<app data>/backups`.
 */
backupDir: string | null, 
/**
 * How long a version check result is reused.
 */
versionCacheMinutes: number, };
