// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { FontFamily } from "./FontFamily";
import type { HiddenAgent } from "./HiddenAgent";
import type { Language } from "./Language";
import type { MonoFont } from "./MonoFont";
import type { ProxyMode } from "./ProxyMode";
import type { Theme } from "./Theme";

export type Settings = { language: Language, theme: Theme, 
/**
 * Accent colour of the interface.
 */
accent: AccentColor, 
/**
 * `#rrggbb` used when `accent` is [`AccentColor::Custom`]; ignored otherwise.
 */
accentCustom: string | null, 
/**
 * Percent that scales spacing, controls, icons and corner radii.
 */
interfaceScale: number, 
/**
 * Percent that scales type only.
 */
textScale: number, 
/**
 * Interface typeface.
 */
fontFamily: FontFamily, 
/**
 * Typeface used for code, paths and the config editor.
 */
monoFont: MonoFont, 
/**
 * Extra directories that are searched for agent binaries and configs.
 */
extraScanPaths: Array<string>, 
/**
 * Turns the optional "a newer version exists" checks on/off (no network by default
 * is *not* the default: they are on, but never block a scan).
 */
networkVersionChecks: boolean, 
/**
 * Overrides where backups go. `None` means `<app data>/backups`.
 */
backupDir: string | null, 
/**
 * How long a version check result is reused.
 */
versionCacheMinutes: number, 
/**
 * How Ahabby reaches the network. Defaults to a direct connection.
 */
proxyMode: ProxyMode, 
/**
 * Manual proxy URL (`http://host:port`); only read when `proxy_mode` is `manual`.
 */
proxyUrl: string | null, 
/**
 * Agents the user removed from Ahabby that are still on disk. A shipped agent (or a
 * user manifest that overrides one) can only be hidden, never deleted.
 */
hiddenAgents: Array<HiddenAgent>, };
