// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFile } from "./ConfigFile";
import type { McpServer } from "./McpServer";
import type { OtherResource } from "./OtherResource";
import type { Skill } from "./Skill";

/**
 * Resources that belong to no single agent: global skills, MCP servers and documents every
 * installed agent can read (`~/.agents/skills`, `~/.agents/mcp.json`, `~/.agents/AGENTS.md`).
 *
 * They travel with the scan report so the Library can show them next to the per-agent
 * resources, and so the backend can resolve them for reading, editing and deletion.
 */
export type SharedResources = { 
/**
 * Files the shared surface declares. They are not listed in the Library, but they are
 * addressable documents — that is how a secret of the shared `mcp.json` is revealed.
 */
configs: Array<ConfigFile>, skills: Array<Skill>, mcpServers: Array<McpServer>, other: Array<OtherResource>, 
/**
 * Resolved roots of the shared surface. A resource an agent manifest also declares
 * under one of them is reported as shared only, never twice.
 */
roots: Array<string>, };
