// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { FrontmatterEntry } from "./FrontmatterEntry";
import type { Scope } from "./Scope";

/**
 * A global skill of one or more agents.
 *
 * The library view merges the *same* skill discovered for several agents into a single
 * entry (see `services::library`), which is why `agents` is a list.
 */
export type Skill = { 
/**
 * Stable id: `<name>#<short path hash>`.
 */
id: string, name: string, description?: string | null, 
/**
 * Directory that holds the skill (what gets trashed when the user deletes it).
 */
path: string, 
/**
 * The markdown file itself, when the skill is file based.
 */
entryPath?: string | null, scope: Scope, agents: Array<AgentRef>, frontmatter: Array<FrontmatterEntry>, 
/**
 * Markdown body (frontmatter stripped). `None` when the skill is a bare directory.
 */
content?: string | null, sizeBytes?: number | null, 
/**
 * `false` for skills Ahabby refuses to delete (e.g. a plugin-managed directory).
 */
removable: boolean, 
/**
 * `true` when the manifest path for this skill has not been verified against docs.
 */
unverified: boolean, };
