// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `set_skill_enabled` switched.
 */
export type SkillToggle = { skillId: string, name: string, 
/**
 * The state the skill is in now.
 */
enabled: boolean, 
/**
 * Where it lives: the skill directory, or the file itself for a document.
 */
path: string, };
