// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend sends to create a skill of its own.
 *
 * Ahabby writes the `SKILL.md` convention (`<skills dir>/<slug>/SKILL.md` with YAML
 * frontmatter), which is what every skills-declaring manifest in the catalog uses. The
 * directory is derived from `name`, so the name is the only required field.
 */
export type SkillDraft = { 
/**
 * Human-readable name; also the `name` of the frontmatter.
 */
name: string, 
/**
 * One-line summary the agents show next to the skill.
 */
description?: string | null, 
/**
 * Markdown body, frontmatter excluded. `None` writes the frontmatter alone.
 */
content?: string | null, };
