// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How skills are stored on disk.
 */
export type SkillFormat = "skillMd" | "directory" | "markdownFile";
