// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsPathMap } from "./OsPathMap";
import type { SkillFormat } from "./SkillFormat";

export type SkillSpec = { format: SkillFormat, path: OsPathMap, 
/**
 * Glob (relative to `path`) that selects skill directories. Defaults to `*`.
 */
glob?: string | null, description?: string | null, };
