// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncComparedFile } from "./SyncComparedFile";
import type { SyncContent } from "./SyncContent";
import type { SyncKind } from "./SyncKind";

/**
 * One item against its cloud copy — what the compare dialog renders.
 */
export type SyncComparison = { key: string, name: string, label: string, kind: SyncKind, ownerId: string, ownerName: string, local: SyncContent, cloud: SyncContent, files: Array<SyncComparedFile>, 
/**
 * Files that differ, are only on one side, or are binary — everything but `Same`.
 */
changed: number, 
/**
 * `true` when every file is byte-identical on both sides.
 */
identical: boolean, };
