// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncProviderId } from "./SyncProviderId";

/**
 * Who the connected account is.
 */
export type SyncAccount = { provider: SyncProviderId, login: string, name?: string | null, avatar?: string | null, 
/**
 * Number of sync gists this account holds, as the last listing saw it.
 */
gists: number, };
