// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a local copy stands relative to the cloud.
 */
export type SyncItemStatus = "unsynced" | "synced" | "modified" | "missing";
