// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncKind } from "./SyncKind";
import type { SyncMode } from "./SyncMode";
import type { SyncProviderId } from "./SyncProviderId";

/**
 * The user's own sync configuration. Non-secret by construction: the token lives in its own
 * file and never enters the settings document (which the frontend reads and writes whole).
 */
export type SyncSettings = { 
/**
 * Master switch. Off means no automatic run and no upload of anything, even by hand.
 */
enabled: boolean, provider: SyncProviderId, mode: SyncMode, 
/**
 * Minutes between two automatic runs. Clamped to [`SyncSettings::MIN_INTERVAL`] ..
 * [`SyncSettings::MAX_INTERVAL`].
 */
autoIntervalMinutes: number, 
/**
 * Kinds automatic saving covers.
 */
autoKinds: Array<SyncKind>, 
/**
 * Owner ids automatic saving covers. Empty = every installed owner.
 */
autoOwners: Array<string>, 
/**
 * Whether an automatic run happens right after a scan, instead of waiting for the timer.
 */
autoOnScan: boolean, 
/**
 * Whether secret-bearing items may be uploaded at all. Off by default: a secret gist is
 * unlisted, not private.
 */
includeSecrets: boolean, 
/**
 * Glob patterns (against the item's relative path) that are never uploaded.
 */
excludePatterns: Array<string>, 
/**
 * Largest item, in bytes, that may be uploaded. Larger items are reported as skipped.
 */
maxFileBytes: number, };
