// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one file of an item stands between this machine and the cloud.
 */
export type SyncFileStatus = "same" | "changed" | "localOnly" | "cloudOnly" | "binary";
