// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which addressable surface an item belongs to.
 */
export type SyncOwnerKind = "agent" | "shared" | "project";
