// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether Ahabby uploads on its own.
 *
 * Uploading is the only thing this governs: *restoring* is always manual, because a cloud copy
 * may never overwrite the machine without the user asking for that one file.
 */
export type SyncMode = "manual" | "automatic";
