// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncFileStatus } from "./SyncFileStatus";

/**
 * One file of a comparison, with the two texts a diff is built from.
 */
export type SyncComparedFile = { path: string, status: SyncFileStatus, binary: boolean, localSizeBytes?: number | null, cloudSizeBytes?: number | null, 
/**
 * The local text, for the diff. `None` when the file is not here or is not text.
 */
left?: string | null, 
/**
 * The cloud text, for the diff. `None` when the copy has no such file or it is not text.
 */
right?: string | null, 
/**
 * `true` when either side was read only in part, so the diff is not the whole story.
 */
truncated: boolean, };
