// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncContentSide } from "./SyncContentSide";
import type { SyncFileContent } from "./SyncFileContent";
import type { SyncKind } from "./SyncKind";

/**
 * One side of an item, read for viewing and comparing.
 */
export type SyncContent = { side: SyncContentSide, key: string, name: string, label: string, ownerId: string, ownerName: string, kind: SyncKind, isDirectory: boolean, 
/**
 * `false` for a declared file that does not exist on this machine (or a copy that is gone).
 */
exists: boolean, files: Array<SyncFileContent>, 
/**
 * Content hash of the whole item, when the reader knows one.
 */
hash?: string | null, 
/**
 * Id of the cloud copy this side belongs to, when there is one.
 */
remoteId?: string | null, uri?: string | null, 
/**
 * When this side was last written: the file's own timestamp, or the copy's `updatedAt`.
 */
modifiedMs?: number | null, };
