// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file inside a [`SyncPayload`]: text as it is, anything else base64.
 */
export type SyncPayloadFile = { 
/**
 * `/`-separated path inside the item (`SKILL.md`, `scripts/render.py`).
 */
path: string, 
/**
 * `utf8` or `base64`.
 */
encoding: string, content: string, };
