// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncKind } from "./SyncKind";
import type { SyncPreviewFile } from "./SyncPreviewFile";

/**
 * What restoring one remote item would do, before anything is written.
 */
export type SyncPreview = { remoteId: string, ownerId: string, ownerName: string, kind: SyncKind, name: string, label: string, 
/**
 * Absolute path a file lands on, or the directory a skill is created in.
 */
destination: string, isDirectory: boolean, canApply: boolean, blockedReason?: string | null, files: Array<SyncPreviewFile>, remoteHash: string, };
