// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncFileAction } from "./SyncFileAction";

/**
 * One file of a pull preview.
 */
export type SyncPreviewFile = { path: string, action: SyncFileAction, sizeBytes: number, binary: boolean, unified?: string | null, };
