// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncAccount } from "./SyncAccount";
import type { SyncMode } from "./SyncMode";
import type { SyncProviderId } from "./SyncProviderId";

/**
 * Everything the Sync screen needs about the connection and the last runs.
 */
export type SyncStatus = { provider: SyncProviderId, enabled: boolean, mode: SyncMode, connected: boolean, tokenHint?: string | null, account?: SyncAccount | null, lastPushMs?: number | null, lastPullMs?: number | null, lastError?: string | null, 
/**
 * `true` while a run (manual or automatic) is in flight.
 */
running: boolean, };
