// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a remote copy lives. Only GitHub Gist is implemented; the enum is what makes a second
 * backend one variant plus one provider file instead of a rewrite.
 */
export type SyncProviderId = "gist";
