// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of an item a reader is looking at.
 */
export type SyncContentSide = "local" | "remote";
