// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncItemStatus } from "./SyncItemStatus";
import type { SyncKind } from "./SyncKind";
import type { SyncOwnerKind } from "./SyncOwnerKind";

/**
 * One addressable thing of one owner — what the UI lists and what a push or a pull addresses.
 */
export type SyncItem = { 
/**
 * Local, path-derived id (`<key>#<hash of the absolute path>`). What a command is addressed
 * by, so two files with the same basename stay distinct on *this* machine.
 */
id: string, 
/**
 * Machine-independent identity inside the owner: `<kind>|<basename>`. What matches a local
 * item to a remote one across machines.
 */
key: string, ownerId: string, ownerName: string, ownerKind: SyncOwnerKind, kind: SyncKind, name: string, label: string, path: string, 
/**
 * Where the item sits, as the owner describes it (`SKILL.md`, `.claude/settings.json`).
 */
relativePath: string, isDirectory: boolean, files: number, sizeBytes: number, editable: boolean, exists: boolean, 
/**
 * `true` when the scan found secret-looking values in it (or it is a `.env` file).
 */
hasSecrets: boolean, status: SyncItemStatus, remoteId?: string | null, remoteUri?: string | null, syncedAtMs?: number | null, };
