// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one synced thing is.
 */
export type SyncKind = "config" | "env" | "skill" | "mcp" | "instruction" | "command" | "subagent" | "hook" | "rule" | "prompt" | "memory" | "other" | "extension";
