// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncKind } from "./SyncKind";
import type { SyncOwnerKind } from "./SyncOwnerKind";
import type { SyncPayloadFile } from "./SyncPayloadFile";

/**
 * The document a provider stores: the item's metadata and its bytes, together.
 *
 * Keeping them in one file is what makes a remote copy self-describing — listing needs no
 * second request, and restoring needs nothing but the file itself.
 */
export type SyncPayload = { schema: number, app: string, kind: SyncKind, key: string, ownerKind: SyncOwnerKind, ownerId: string, ownerName: string, name: string, label: string, relativePath: string, isDirectory: boolean, files: Array<SyncPayloadFile>, hash: string, pushedAtMs: number, sourcePath: string, appVersion: string, os: string, 
/**
 * `true` when the payload deliberately carries secret-looking values.
 */
hasSecrets: boolean, };
