// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to restore, and where: one cloud copy and the owner that should receive it.
 */
export type SyncPullTarget = { remoteId: string, ownerId: string, };
