// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a push, a pull, a delete or an automatic run did.
 */
export type SyncRunKind = "push" | "pull" | "delete" | "automatic";
