// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Address of one local item, as a command receives it.
 */
export type SyncItemRef = { ownerId: string, itemId: string, };
