// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a pull would do to one file.
 */
export type SyncFileAction = "add" | "replace" | "same" | "blocked";
