// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncItemResult } from "./SyncItemResult";
import type { SyncRunKind } from "./SyncRunKind";

export type SyncRun = { kind: SyncRunKind, uploaded: number, downloaded: number, deleted: number, skipped: number, failed: number, results: Array<SyncItemResult>, atMs: number, };
