// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of an item, as a reader shows it.
 *
 * The text is what the viewer renders; a binary file carries none and is reported by its size
 * alone, so a skill's asset never arrives as half a megabyte of base64 nobody can read. The
 * hash is over the *whole* file, which is what lets two binaries be compared at all.
 */
export type SyncFileContent = { 
/**
 * `/`-separated path inside the item (`SKILL.md`, `scripts/render.py`).
 */
path: string, 
/**
 * The text, when the file is text and inside the viewer's limit.
 */
text: string | null, sizeBytes: number, binary: boolean, 
/**
 * `true` when the file is larger than the viewer reads — `text` is its beginning.
 */
truncated: boolean, 
/**
 * `sha256:<hex>` of the whole file, cut or not.
 */
hash?: string | null, };
