// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncRun } from "./SyncRun";

/**
 * What the `sync://done` event carries: the run, or the error that stopped it before it began.
 */
export type SyncEvent = { run?: SyncRun | null, error?: string | null, };
