// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncKind } from "./SyncKind";

/**
 * Outcome of one item inside a run.
 */
export type SyncItemResult = { name: string, ownerId: string, kind: SyncKind, ok: boolean, skipped: boolean, message?: string | null, remoteId?: string | null, };
