// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncItem } from "./SyncItem";

/**
 * The local half of the Sync library.
 */
export type SyncItemList = { items: Array<SyncItem>, 
/**
 * Items the user has not uploaded yet.
 */
unsynced: number, 
/**
 * Items whose local content changed since the last upload.
 */
modified: number, 
/**
 * Items that were uploaded but are no longer on disk.
 */
missing: number, };
