// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Colour scheme painted by the built-in terminal.
 *
 * `Auto` follows the rest of the interface — the app theme, the accent and the design tokens —
 * while every other variant names a fixed palette. The list is what *validates* the setting: the
 * frontend owns the hexes (`src/features/terminal/lib/themes.ts`) but only for the ids declared
 * here, so a hand-edited file cannot ask for a scheme nobody can paint.
 */
export type TerminalTheme = "auto" | "one-dark" | "dracula" | "nord" | "gruvbox" | "tokyo-night" | "catppuccin" | "solarized-dark" | "solarized-light" | "one-light";
