// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk of PTY output.
 *
 * `data` is base64: a read can split a UTF-8 sequence in the middle, so the raw bytes travel
 * losslessly and are decoded into the terminal's own UTF-8 decoder in the frontend.
 */
export type TerminalOutput = { sessionId: string, data: string, };
