// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a terminal can be asked to do with an agent.
 */
export type TerminalCapability = "runsCommand" | "opensDirectory";
