// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalCapability } from "./TerminalCapability";
import type { TerminalKind } from "./TerminalKind";

/**
 * One entry of the terminal picker in Settings.
 */
export type TerminalOption = { id: string, name: string, kind: TerminalKind, capability: TerminalCapability, 
/**
 * Where the terminal was found; `None` for the built-in one.
 */
path?: string | null, };
