// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalOption } from "./TerminalOption";

/**
 * The picker's options plus the directory a new session starts in.
 */
export type TerminalCatalog = { options: Array<TerminalOption>, 
/**
 * Home directory, offered as the default working directory.
 */
defaultCwd: string, };
