// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The process inside a session ended (the tab stays open until the user closes it).
 */
export type TerminalExit = { sessionId: string, exitCode?: number | null, };
