// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A live (or already finished) terminal session.
 */
export type TerminalSession = { id: string, agentId: string, agentName: string, 
/**
 * Directory the shell was started in.
 */
cwd: string, 
/**
 * The shell the session runs.
 */
shell: string, 
/**
 * The command line that was typed into the shell (the agent binary).
 */
command: string, cols: number, rows: number, running: boolean, exitCode?: number | null, startedAtMs: number, };
