// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional "a newer version exists" information.
 */
export type UpdateInfo = { latest: string, 
/**
 * `npm` or `github`, for the UI tooltip.
 */
source: string, checkedAtMs: number, };
