// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A version string produced by an agent's CLI, together with the numeric parts
 * we managed to recover from it.
 *
 * `raw` is kept verbatim (that is what the UI shows); the numeric parts are only
 * used for "is there an update" comparisons and are allowed to be zero when the
 * CLI prints something exotic — in that case [`Version::comparable`] is `false`.
 */
export type Version = { raw: string, major: number, minor: number, patch: number, prerelease?: string | null, 
/**
 * Whether the numeric parts were recovered from `raw` (and are therefore trustworthy).
 */
comparable: boolean, };
