// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An image carried through the backend, so the window never loads a remote origin.
 */
export type WebImage = { mime: string, base64: string, };
