// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebPageKind } from "./WebPageKind";

/**
 * One document read for the reader, after redirects.
 *
 * The body is the document as the server sent it (decoded, not rewritten): the frontend
 * sanitizes it before it reaches the DOM, so nothing here has to guess what is safe.
 */
export type WebPage = { 
/**
 * The address the page was actually read from, which is what its relative links resolve to.
 */
url: string, kind: WebPageKind, body: string, 
/**
 * True when the document was longer than the reader's ceiling and was cut.
 */
truncated: boolean, };
