// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of Ahabby's one window, for the header it draws itself.
 *
 * The header is the app's own only where the OS frame is gone (`custom`); elsewhere the
 * window wears the frame macOS or Linux gives it and this model is read but not drawn.
 * `maximized` and `focused` are pushed as they change — by the window's own event handler,
 * never polled — because a maximized window is what turns the middle button into a restore,
 * and the OS dims an inactive window's controls.
 */
export type WindowChrome = { 
/**
 * The window has no OS frame, so the app draws its own header.
 */
custom: boolean, 
/**
 * The window is maximized (restore is what the header's middle button then does).
 */
maximized: boolean, 
/**
 * The window is the active one.
 */
focused: boolean, };
